'use client';
import {lowDiscrimination,highDifficulty,reviewReasons} from './item-review-flags';
import {useState} from 'react';
type Item={id:number;no:string;area:string;topic:string;b:number;a:number;warning:boolean;major:number;stem:string};
const colors=['#087f83','#4169ba','#9a59b5','#c27b24','#cf5569','#527c3b'];
export default function ItemCurves({items,onOpen}:{items:Item[];onOpen:(id:number)=>void}){
 const [group,setGroup]=useState(0),[active,setActive]=useState<number|null>(null);
 const shown=items.filter(i=>!group||i.major===group);
 const selected=shown.find(i=>i.id===active);

 return <section className="card below icc-panel"><div className="sectionhead compact"><div><h2>項目特性曲線</h2><p className="muted">大問6問・採点単位30問 / 枝問のない小問、または各枝問につき1本</p></div><span className="badge">2PL</span></div><div className="chips">{[0,1,2,3,4,5,6].map(g=><button key={g} className={group===g?'on':''} onClick={()=>{setGroup(g);setActive(null)}}>{g?<><i style={{background:colors[g-1]}}/>大問{g}</>:'全30問'}</button>)}</div><div className="icc-layout"><div><IrtPlot shown={shown} active={active} onSelect={setActive}/><p className="footnote">破線は、見直した方がよい問題（要確認）です。下のピンクの設問ボタンが対応しています。曲線または設問ボタンにマウスを重ねると、対応するボタンの枠が濃くなり、右側に問題文を表示します。点線は正答確率50%です。</p></div><aside className="icc-selection"><h3>{selected?`設問 ${selected.no}`:'設問を選択'}</h3>{selected?<><div className="icc-stem"><small>問題文</small><p title={selected.stem}>{selected.stem}</p></div><p>{selected.area}</p><p>{selected.topic}</p><dl><dt>難易度 b</dt><dd><span className={highDifficulty(selected.b)?'metric-warning':undefined}>{selected.b.toFixed(2)}</span></dd><dt>識別力 a</dt><dd><span className={lowDiscrimination(selected.a)?'metric-warning':undefined}>{selected.a.toFixed(2)}</span></dd></dl>{selected.warning&&<span className="badge amber">{reviewReasons(selected)}</span>}<button className="primary full" onClick={()=>onOpen(selected.id)}>問題の詳細を見る →</button></>:<p className="muted">曲線の位置と傾きを比較し、気になる問題の内容や答案を確認できます。</p>}</aside></div><div className="icc-items">{shown.map(i=><button key={i.id} className={i.warning?'icc-review-button':undefined} aria-label={`設問 ${i.no}${i.warning?'・見直し候補':''}の問題文を見る`} aria-pressed={active===i.id} onMouseEnter={()=>setActive(i.id)} onFocus={()=>setActive(i.id)} onClick={()=>setActive(i.id)} style={{borderColor:active===i.id?colors[i.major-1]:undefined}}><i style={{background:colors[i.major-1]}}/>{i.no}{i.warning?' ⚑':''}</button>)}</div></section>
}

export function IrtPlot({shown,active=null,onSelect}:{shown:Item[];active?:number|null;onSelect?:(id:number)=>void}){
 const path=(i:Item)=>Array.from({length:161},(_,n)=>{const x=-4+n/20,p=1/(1+Math.exp(-i.a*(x-i.b)));return `${60+n*4.25},${(310-p*270).toFixed(4)}`}).join(' ');
return <svg viewBox="0 0 780 370" role="img" aria-label={shown.length===1?`設問 ${shown[0].no} の項目特性曲線`:`${shown.length}問の項目特性曲線`} className="icc-chart">{[0,.25,.5,.75,1].map(p=><g key={p}><line x1="60" x2="740" y1={310-p*270} y2={310-p*270} stroke="#dde6ec" strokeDasharray={p===.5?'5 5':undefined}/><text x="47" y={315-p*270} textAnchor="end" fill="#657b89" fontSize="13">{p.toFixed(2)}</text></g>)}{[-4,-3,-2,-1,0,1,2,3,4].map(x=><g key={x}><line x1={60+(x+4)*85} x2={60+(x+4)*85} y1="40" y2="310" stroke="#f0f3f6"/><text x={60+(x+4)*85} y="335" textAnchor="middle" fill="#657b89" fontSize="13">{x}</text></g>)}<text x="60" y="22" fontSize="14" fill="#345566">正答確率</text><text x="400" y="363" textAnchor="middle" fontSize="14" fill="#345566">能力値 θ（低い ← → 高い）</text>{[...shown].sort((a,b)=>(Number(a.id===active)*2+Number(a.warning))-(Number(b.id===active)*2+Number(b.warning))).map(i=><polyline key={i.id} points={path(i)} fill="none" stroke={colors[i.major-1]} strokeDasharray={i.warning?'9 5':undefined} strokeWidth={active===i.id?4.5:i.warning?3.2:1.5} opacity={active===null?(i.warning?1:.42):active===i.id?1:i.warning?.4:.12} onMouseEnter={()=>onSelect?.(i.id)} onClick={()=>onSelect?.(i.id)} style={{cursor:'pointer'}}><title>{`設問 ${i.no} / ${i.topic} / 難易度 ${i.b} / 識別力 ${i.a}`}</title></polyline>)}</svg>;
}
