'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {Sparkles} from 'lucide-react';
type Item={id:number;no:string;area:string;unit:string;topic:string;stem:string};
// Explicit LRT illustration data; not calculated from IRT parameters or actual responses.
const profiles=[[12,63,83,94],[8,19,74,91],[4,12,27,81],[18,40,66,88],[32,48,60,71],[7,13,69,90]];
export function rankProfile(id:number){const p=profiles[id%profiles.length];return {p,uncertain:id===13,gaps:p.slice(1).map((v,i)=>v-p[i])};}
function Conditions(){const [open,setOpen]=useState(false);return <><button className="textlink" onClick={()=>setOpen(true)}>4段階（固定） · 分析条件を見る</button><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogTitle>学力段階の分析条件</DialogTitle><DialogDescription>学力段階は4段階固定です。段階数の選択や追加の入力は不要です。</DialogDescription><p>数学全体の正誤データから、学力を段階1〜4の4段階として推定する設計です。段階4ほど高い学力を表します。</p><p>領域別の表示にも、この共通の4段階を使います。領域ごとに別の学力段階を推定するものではありません。</p><p className="muted">本製品では各段階の人数や推定の安定性を確認し、不安定な結果は判定を保留する設計です。未回答はデータ上で区別して保持し、分析での扱いは確定後にここへ表示します。</p><p className="footnote">このモックの正答確率は説明用データです。実際の推定は行っていません。段階間の差が30ポイント以上の問題を候補にする基準はモック用の目安で、潜在ランク理論そのものの基準ではありません。</p></DialogContent></Dialog></>}
export function RankDetail({item}:{item:Item}){const {p,gaps,uncertain}=rankProfile(item.id);const peak=gaps.indexOf(Math.max(...gaps));return <section className="card below"><div className="sectionhead compact"><div><h2>学力段階別の正答確率</h2><p className="muted">潜在ランク理論（LRT） · 説明用データ</p></div><Conditions/></div><svg viewBox="0 0 560 205" className="curve" role="img" aria-label={`設問${item.no}の段階別正答確率 ${p.join('、')}パーセント`}>{[0,50,100].map(v=><g key={v}><line x1="50" x2="510" y1={160-v*1.25} y2={160-v*1.25} stroke="#dfe8ee"/><text x="10" y={165-v*1.25} fontSize="12" fill="#597383">{v}%</text></g>)}<polyline points={p.map((v,i)=>`${65+i*140},${160-v*1.25}`).join(' ')} fill="none" stroke="#087f83" strokeWidth="3"/>{p.map((v,i)=><g key={i}><circle cx={65+i*140} cy={160-v*1.25} r="5" fill="#087f83"/><text x={65+i*140} y={150-v*1.25} textAnchor="middle" fontSize="13">{v}%</text><text x={65+i*140} y="187" textAnchor="middle" fontSize="13">段階{i+1}</text></g>)}</svg><div className="callout"><b>{uncertain?'推定が不安定な例：段階間の候補判定を保留しています':`段階${peak+1}から${peak+2}で、正答確率が${gaps[peak]}ポイント上がっています。`}</b><p>{uncertain?'答案やデータ数を確認してから解釈します。':Math.max(...gaps)>=30?'この段階間の違いを捉える問題の候補です。問題内容と答案を合わせて確認してください。':''}</p></div><p className="footnote">段階はこの数学テスト内の学力の順序です。発達年齢や単元の習得認定ではありません。</p></section>}
export default function RankSummary({items,onOpen}:{items:Item[];onOpen:(id:number)=>void}){const [area,setArea]=useState('全領域'),[boundary,setBoundary]=useState<number|null>(null),[ai,setAi]=useState(false);const areas=[...new Set(items.map(i=>i.area))];const chosen=items.filter(i=>(area==='全領域'||i.area===area)&&(boundary===null||(!rankProfile(i.id).uncertain&&rankProfile(i.id).gaps[boundary]>=30)));const count=(a:string,b:number)=>items.filter(i=>i.area===a&&!rankProfile(i.id).uncertain&&rankProfile(i.id).gaps[b]>=30).length;
return <section className="card below"><div className="sectionhead compact"><div><h2>学力段階から見た出題構成</h2><p className="muted">どの領域で、どの学力段階の違いを捉える問題が揃っているか</p></div><button className="primary" onClick={()=>setAi(!ai)}><Sparkles size={17}/>AIに次回の出題構成を相談</button></div><Conditions/><Table><TableHeader><TableRow><TableHead>領域</TableHead>{[1,2,3].map(n=><TableHead key={n}>段階{n}と{n+1}を見分ける問題</TableHead>)}<TableHead>対象問題数</TableHead></TableRow></TableHeader><TableBody>{areas.map(a=><TableRow key={a}><TableCell><button className="textlink" onClick={()=>{setArea(a);setBoundary(null)}}>{a}</button></TableCell>{[0,1,2].map(b=><TableCell key={b}><button className="secondary" onClick={()=>{setArea(a);setBoundary(b)}}>{count(a,b)}問</button></TableCell>)}<TableCell>{items.filter(i=>i.area===a).length}問</TableCell></TableRow>)}</TableBody></Table><p className="footnote">各セルは、隣り合う学力段階で正答確率の差が大きい問題の候補数です。生徒の成長や段階の移動を示すものではありません。複数列に該当する場合もあり、行の合計は問題総数と一致しません。</p><div className="callout"><b>次回の出題に向けた確認</b><p>{area==='全領域'?'領域ごとの候補数を見て、次回に測りたい学力層に対応する問題が揃っているか確認してください。':`${area}では、段階1と2を見分ける問題が${count(area,0)}問、段階2と3を見分ける問題が${count(area,1)}問、段階3と4を見分ける問題が${count(area,2)}問の候補です。対象層と出題範囲に照らして配分を確認してください。`}</p></div>{ai&&<div className="insight below"><h3>AIからの検討案（定型回答）</h3><p>相談対象：数学 / {area}</p><p>候補数が少ない段階間について、既存問題の単元・学習項目を確認しましょう。次回もその層を測る予定なら、同じ学習項目で条件や解答の負担を調整した問題を追加する案が考えられます。均等な配分を目指す必要はありません。</p><p className="footnote">実際のAIには送信しません。問題の追加や設定変更は行いません。</p></div>}<div className="sectionhead"><h3>問題ごとの段階別正答確率 · {chosen.length}問</h3><button className="textlink" onClick={()=>{setArea('全領域');setBoundary(null)}}>全30問を表示</button></div><p className="muted">{area}{boundary!==null?` / 段階${boundary+1}と${boundary+2}を見分ける問題の候補`:''} · 色が濃いほど正答確率が高い</p><div style={{maxHeight:420,overflow:'auto'}}><Table><TableHeader><TableRow><TableHead>設問 / 単元・学習項目</TableHead>{[1,2,3,4].map(n=><TableHead key={n}>段階{n}</TableHead>)}<TableHead>推定状態</TableHead></TableRow></TableHeader><TableBody>{chosen.map(i=><TableRow key={i.id}><TableCell><button className="textlink" onClick={()=>onOpen(i.id)}>{i.no} · {i.unit}</button><p className="muted">{i.topic}</p></TableCell>{rankProfile(i.id).p.map((v,n)=><TableCell key={n} style={{background:`rgba(8,127,131,${v/140})`,color:v>65?'white':'#173e49',textAlign:'center'}}>{v}%</TableCell>)}<TableCell>{rankProfile(i.id).uncertain?'不安定・例':'推定済み・例'}</TableCell></TableRow>)}</TableBody></Table>{chosen.length===0&&<p className="empty">この条件に該当する候補はありません。</p>}</div></section>}
