'use client';
import {useState} from 'react';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
type Test={id:string;name:string;start:string;end:string;demo:boolean};
type Item={id:number;area:string;unit:string;topic:string;point:number;rate:number};
const schools=['青葉中学校','桜丘中学校','若葉中学校','みなと中学校','緑台中学校','山手中学校'];
const sizes=[96,84,108,72,90,30];
export default function SchoolTrends({tests,subject,items,onOpen}:{tests:Test[];subject:string;items:Item[];onOpen:(id:string,subject:string)=>void}){
 const [metric,setMetric]=useState('平均点'),[classification,setClassification]=useState<'area'|'unit'|'topic'>('area'),[label,setLabel]=useState(''),[detail,setDetail]=useState<{school:number;test:Test}|null>(null),[search,setSearch]=useState('');
 const labels=[...new Set(items.map(i=>i[classification]))],chosen=labels.includes(label)?label:labels[0];
 const data=(t:Test,s:number,category='')=>{if(!t.demo)return null;const n=t.id==='t1'?sizes[s]-3:sizes[s];const low=s===2&&t.id!=='t1';const avg=58+(s%3)*3-s*1.7+(t.id==='t1'?3:0)-(low?10:0);return {n,avg,blank:low?12:2+s*.5,rate:Math.max(0,Math.min(100,avg+(category.length%7)-3-(low&&category===(subject==='数学'?'関数':labels[1])?18:0)))}};
 const mean=(t:Test,category='')=>{let sum=0,n=0;schools.forEach((_,s)=>{const d=data(t,s,category);if(d){sum+=(metric==='分類別得点率'?d.rate:d.avg)*d.n;n+=d.n}});return n?sum/n:0};
 return <section className="below"><h3>学校別の推移 · {subject}</h3><p className="muted">学校名を固定して各回を横に比較できます。セルを選ぶと、その学校・その回の詳細を表示します。</p><div className="actions below"><input className="school-search" aria-label="学校名検索" placeholder="学校名で検索" value={search} onChange={e=>setSearch(e.target.value)}/><label>表示指標 <select value={metric} onChange={e=>setMetric(e.target.value)}>{['平均点','受験者数','未回答率','分類別得点率'].map(m=><option key={m}>{m}</option>)}</select></label>{metric==='分類別得点率'&&<><select aria-label="分類の種類" value={classification} onChange={e=>{setClassification(e.target.value as typeof classification);setLabel('')}}><option value="area">領域</option><option value="unit">単元</option><option value="topic">学習項目</option></select><select aria-label="比較する分類" value={chosen} onChange={e=>setLabel(e.target.value)}>{labels.map(l=><option key={l}>{l}</option>)}</select></>}</div><div className="card below school-table" tabIndex={0} role="region" aria-label="学校別・各回の推移"><Table style={{minWidth:180+tests.length*210}}><TableHeader><TableRow><TableHead>学校名</TableHead>{tests.map(t=><TableHead key={t.id}>{t.name}<p>{t.start}</p></TableHead>)}</TableRow></TableHeader><TableBody>{schools.map((name,s)=>name.includes(search)&&<TableRow key={name}><TableCell><b>{name}</b></TableCell>{tests.map(t=>{const d=data(t,s,chosen);if(!d)return <TableCell key={t.id}>—</TableCell>;const value=metric==='平均点'?d.avg:metric==='受験者数'?d.n:metric==='未回答率'?d.blank:d.rate;const delta=value-mean(t,chosen);return <TableCell key={t.id}><button className="textlink" onClick={()=>setDetail({school:s,test:t})}>{metric==='受験者数'?value:value.toFixed(1)}{metric==='平均点'?'点':metric==='受験者数'?'人':'%'}</button>{['平均点','分類別得点率'].includes(metric)&&<small className={`review-reason ${delta>0?'school-positive':''}`}>全体比 {delta>0?'+':''}{delta.toFixed(1)}{metric==='平均点'?'点':'pt'}</small>}</TableCell>})}</TableRow>)}</TableBody></Table></div><p className="footnote">「—」は比較できるデータがない回です。得点の変化には出題内容・難易度・受験者層が影響します。学力の伸びや未習を断定するものではありません。</p>{detail&&<div className="card below"><div className="sectionhead"><h3>{schools[detail.school]} / {detail.test.name}</h3><button className="textlink" onClick={()=>setDetail(null)}>閉じる</button></div><p>受験者数 {data(detail.test,detail.school)?.n}人 / 平均点 {data(detail.test,detail.school)?.avg.toFixed(1)}点 / 未回答率 {data(detail.test,detail.school)?.blank.toFixed(1)}%</p><Table><TableHeader><TableRow><TableHead>領域</TableHead><TableHead>得点率</TableHead></TableRow></TableHeader><TableBody>{[...new Set(items.map(i=>i.area))].map(a=><TableRow key={a}><TableCell>{a}</TableCell><TableCell>{data(detail.test,detail.school,a)?.rate.toFixed(1)}%</TableCell></TableRow>)}</TableBody></Table><button className="secondary below" onClick={()=>onOpen(detail.test.id,subject)}>この回の分析へ →</button></div>}</section>
}
