'use client';
import SchoolTrends from './school-trends';
import {useState} from 'react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
type Test={id:string;name:string;start:string;end:string;demo:boolean};
const subjects=['国語','数学','英語','理科','社会'];
const areas=['数と式','関数','図形','資料の活用'];
const colors=['#087f83','#477bc1','#b2834b','#7d68a3'];
const profiles=[{points:[30,37,18,15],counts:[8,11,6,5],bins:[9,3,6,3,9],n:480,box:[8,43,59,74,98]},{points:[35,28,25,12],counts:[10,8,8,4],bins:[5,5,12,5,3],n:462,box:[12,46,62,77,99]}];
export default function SeriesComparison({tests,onOpen,subject,items}:{subject:string;items:{id:number;area:string;unit:string;topic:string;point:number;rate:number}[];tests:Test[];onOpen:(id:string,subject:string)=>void}){
 const view=subject;const [metric,setMetric]=useState('配点');
 const [section,setSection]=useState('sets');
 const rounds=[...tests].sort((a,b)=>a.start.localeCompare(b.start));
 const profile=(t:Test)=>profiles[t.id==='t1'?1:0];
 const columns={gridTemplateColumns:`repeat(${Math.max(1,rounds.length)}, 250px)`};
 const row=(render:(t:Test)=>React.ReactNode)=><div className="round-compare-row" style={columns}>{rounds.map(t=><div className="round-compare-cell" key={t.id}>{render(t)}</div>)}</div>;
 return <section className="series-comparison"><Tabs value={section} onValueChange={v=>setSection(String(v))}><TabsList variant="line" className="viewtabs"><TabsTrigger value="sets">問題セットの比較</TabsTrigger><TabsTrigger value="schools">学校別の推移</TabsTrigger></TabsList></Tabs>
 {section==='schools'?<SchoolTrends tests={rounds} subject={subject} items={items} onOpen={onOpen}/>:subject!=='数学'?<div className="card empty">{view}の比較は準備中です。数学の各回比較をご覧ください。</div>:rounds.length===0?<div className="card empty">テストを登録すると各回を比較できます。</div>:<><p className="footnote">実施開始日の順に表示しています。横にスクロールすると、同じ回の構成と得点分布を縦に見比べられます。</p><div className="round-compare-scroll" tabIndex={0} role="region" aria-label="各回比較・横スクロール"><div className="round-compare-sheet" style={{width:Math.max(1,rounds.length)*250}}>
 {row(t=><><h3>{t.name}</h3><p className="muted">{t.start} ～ {t.end}</p><button className="textlink" onClick={()=>onOpen(t.id,view==='all'?'数学':view)}>各回の分析へ →</button></>)}
 {view==='all'?<>{subjects.map((sub,i)=><div key={sub}><h3 className="round-section-title">{sub}の問題セット</h3>{row(t=><>{t.demo?<><b>{sub==='数学'?'30問・100点':'24問・100点'}</b><p>{sub==='数学'?(t.id==='t1'?'関数28%・図形25%':'関数37%・図形18%'):['文章と語句の配分','', '読解と語彙・文法の配分','4領域の配分','地理・歴史・公民の配分'][i]}</p><button className="textlink" onClick={()=>sub==='数学'?onOpen(t.id,'数学'):onOpen(t.id,sub)}>教科の構成を比較 →</button></>:<span className="muted">データ未登録</span>}</>)}</div>)}</>:<>
 <h3 className="round-section-title">比較の前提</h3>{row(t=><>{t.demo?<dl className="round-facts"><dt>受験者数</dt><dd>{profile(t).n}人</dd><dt>大問数</dt><dd>6問</dd><dt>採点単位問題数</dt><dd>30問</dd><dt>満点</dt><dd>100点</dd><dt>要確認問題数</dt><dd>{t.id==='t1'?2:6}問</dd></dl>:<p>データ未登録</p>}</>)}
 <h3 className="round-section-title">出題内容の構成 <span className="chips">{['配点','問題数'].map(m=><button key={m} className={metric===m?'on':''} onClick={()=>setMetric(m)}>{m}</button>)}</span></h3>{row(t=>t.demo?<><div className="vertical-composition">{areas.map((a,i)=>{const value=metric==='配点'?profile(t).points[i]:profile(t).counts[i]/30*100;return <div key={a} style={{height:value+'%',background:colors[i]}} title={`${a}：${value.toFixed(1)}%`}>{metric==='配点'?profile(t).points[i]+'%':profile(t).counts[i]+'問'}</div>})}</div><div className="stack-legend">{areas.map((a,i)=><span key={a}><i style={{background:colors[i]}}/>{a}</span>)}</div></>:<p>データ未登録</p>)}
 <h3 className="round-section-title">難易度の構成</h3>{row(t=>t.demo?<div className="round-bins">{profile(t).bins.map((n,i)=><div key={i}><b>{n}</b><div style={{height:n*8,background:'#087f83',width:25}}/><small>{['≤−1','−1〜−.5','−.5〜.5','.5〜1','≥1'][i]}</small></div>)}<p>低い ← 難易度 b → 高い</p></div>:<p>データ未登録</p>)}
 <h3 className="round-section-title">得点分布（箱ひげ図）</h3>{row(t=>{if(!t.demo)return <p>データ未登録</p>;const [min,q1,median,q3,max]=profile(t).box;const y=(v:number)=>220-v*2;return <><svg viewBox="0 0 220 255" role="img" aria-label={`${t.name} 最低${min}点、第1四分位${q1}点、中央値${median}点、第3四分位${q3}点、最高${max}点`}>{[0,25,50,75,100].map(n=><g key={n}><line x1="35" x2="200" y1={y(n)} y2={y(n)} stroke="#e0e8ed"/><text x="28" y={y(n)+4} textAnchor="end" fontSize="11">{n}</text></g>)}<line x1="115" x2="115" y1={y(max)} y2={y(min)} stroke="#087f83" strokeWidth="2"/>{[min,max].map(n=><line key={n} x1="92" x2="138" y1={y(n)} y2={y(n)} stroke="#087f83" strokeWidth="2"/>)}<rect x="80" y={y(q3)} width="70" height={y(q1)-y(q3)} fill="#d7eeef" stroke="#087f83" strokeWidth="2"/><line x1="80" x2="150" y1={y(median)} y2={y(median)} stroke="#173e49" strokeWidth="3"/><text x="160" y={y(median)+4} fontSize="12">{median}</text><text x="115" y="245" textAnchor="middle" fontSize="12">得点（100点満点）</text></svg><p>中央値 <b>{median}点</b> / 中央50%：{q1}〜{q3}点</p></>})}
 </>}
 </div></div>{view==='数学'&&<section className="card below"><h3>学力層ごとの測定精度</h3><p className="muted">各回を同じ軸で重ねて比較します。曲線が高い学力層ほど、測定精度が高くなります。</p><svg viewBox="0 0 800 300" style={{width:'100%',maxHeight:340}} role="img" aria-label="各回のテスト情報曲線を重ねた比較グラフ">{[0,5,10,15,20].map(n=><g key={n}><line x1="50" x2="750" y1={245-n*10} y2={245-n*10} stroke="#e0e8ed"/><text x="38" y={249-n*10} textAnchor="end" fontSize="12">{n}</text></g>)}{rounds.filter(t=>t.demo).map((t,j)=><polyline key={t.id} fill="none" stroke={`hsl(${j*137.5+180} 55% 40%)`} strokeWidth="3" strokeDasharray={j%2?'7 4':undefined} points={Array.from({length:121},(_,i)=>{const x=-3+i/20;return `${50+i*700/120},${245-200*Math.exp(-Math.pow(x-(t.id==='t1'?0:.3),2)/(t.id==='t1'?1.7:2.4))}`}).join(' ')}><title>{t.name}</title></polyline>)}{[-3,-2,-1,0,1,2,3].map(n=><text key={n} x={50+(n+3)*700/6} y="267" textAnchor="middle" fontSize="12">{n}</text>)}<text x="50" y="23" fontSize="12">情報量</text><text x="400" y="292" textAnchor="middle" fontSize="12">能力値 θ</text></svg><div className="measurement-legend">{rounds.filter(t=>t.demo).map((t,j)=><span key={t.id}><i style={{borderTop:`3px ${j%2?'dashed':'solid'} hsl(${j*137.5+180} 55% 40%)`}}/>{t.name}</span>)}</div></section>}{view==='数学'&&<p className="footnote">箱は中央50%の生徒の得点範囲、箱の中の線は中央値、ひげは最低点〜最高点です。得点差には受験者層と問題の難易度の両方が影響するため、学力の伸びだけを示すものではありません。箱ひげ図は表示確認用の仮の集計値です。</p>}</>}
 </section>
}
